// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

const Ethers = require('ethers');

const min_eth_amount = Ethers.ethers.BigNumber.from('100000000000000000');

const gas_multiple = Ethers.ethers.BigNumber.from('2');

const credentials = {
  accessKeyId: '',
  secretAccessKey: '',
};

const sell_amount = '100000000000000000';

const profit_threshold = 2.0;

const stoploss_threshold = 0.1;

const discord_token = '';

const discord_guild = '';

const discord_channel = '';

const endpoint = '';

const eth_wallet_address = '';

const eth_wallet_private_key = '';

const infura_project_id = '';

const infura_project_secret = '';

exports.sell_amount = sell_amount;
exports.min_eth_amount = min_eth_amount;
exports.gas_multiple = gas_multiple;
exports.profit_threshold = profit_threshold;
exports.stoploss_threshold = stoploss_threshold;
exports.discord_token = discord_token;
exports.discord_guild = discord_guild;
exports.discord_channel = discord_channel;
exports.endpoint = endpoint;
exports.credentials = credentials;
exports.eth_wallet_address = eth_wallet_address;
exports.eth_wallet_private_key = eth_wallet_private_key;
exports.infura_project_id = infura_project_id;
exports.infura_project_secret = infura_project_secret;
/* min_eth_amount Not a pure module */
