// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var InvalidResponse = /* @__PURE__ */Caml_exceptions.create("Types.InvalidResponse");

exports.InvalidResponse = InvalidResponse;
/* No side effect */
